# Only enable linters for Java, JavaScript, HTML, and CSS
DISABLE_ALL: true

ENABLE:
  - JAVA
  - JAVASCRIPT
  - HTML
  - CSS

# Enable automatic fixing
ENABLE_LINTER_FIXERS: true  # ✅ Enables autofix for supported linters

# Java Linters (Static Analysis + Code Style)
JAVA:
  ENABLE:
    - CHECKSTYLE
    - SPOTBUGS
    - PMD

# JavaScript Linters (Best Practices + Fixes)
JAVASCRIPT:
  ENABLE:
    - ESLINT
  ESLINT_CONFIG:
    autofix: true  # ✅ Enables ESLint autofix

# HTML Linters + Fixing
HTML:
  ENABLE:
    - HTMLHINT
  HTMLHINT_CONFIG:
    autofix: true  # ✅ Enables HTMLHint autofix

# CSS Linters + Fixing
CSS:
  ENABLE:
    - STYLELINT
  STYLELINT_CONFIG:
    autofix: true  # ✅ Enables Stylelint autofix

# Remove fun ASCII Alpaca logs
PRINT_ALPACA: false