name: Deploy Spring Boot to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      SPRING_PROFILES_ACTIVE: test  # Ensures application-test.properties is used
      TESTDB_URL: jdbc:tc:mysql:8.0:///testdb
      TESTDB_USERNAME: root
      TESTDB_PASSWORD: chip1852
      COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
      COHERE_API_MODEL: command-r-plus
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Debug Environment Variables
        run: env | sort  # Print all environment variables

      - name: Verify Active Spring Profile
        run: echo "Active profile is $SPRING_PROFILES_ACTIVE"

      - name: Debug Active Profile and Database URL
        run: |
          echo "Active Profile: $SPRING_PROFILES_ACTIVE"
          echo "Test DB URL: $TESTDB_URL"
          echo "Test DB Username: $TESTDB_USERNAME"
          echo "Test DB Password: $TESTDB_PASSWORD"
      
      - name: Debug API Key Length
        run: |
          if [ -z "${{ secrets.COHERE_API_KEY }}" ]; then
            echo "COHERE_API_KEY is NOT set!"
          else
            echo "COHERE_API_KEY is set and has a length of ${#COHERE_API_KEY} characters."
          fi
        shell: bash
      
      - name: Test API Connectivity
        run: |
          curl -H "Authorization: Bearer $COHERE_API_KEY" -X POST https://api.cohere.ai/v1/chat || echo "API call failed"

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Run Unit Tests
        run: SPRING_PROFILES_ACTIVE=test ./gradlew test --stacktrace --info

      - name: Run API Integration Tests with Testcontainers
        run: ./gradlew apiTest

      # - name: Run UI Tests (Selenium)
      #   run: ./gradlew seleniumTest

      # - name: Run Performance Tests
      #   run: ./gradlew performanceTest

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: "grading-system"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          slot-name: 'Production'
          package: build/libs/tesla-0.0.1-SNAPSHOT.jar

      - name: Check Deployment Health
        run: |
          sleep 20  # Give the server some time to start
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://grading-system-c3fmdra0ehedhufq.canadacentral-01.azurewebsites.net/health)
          if [ "$STATUS" -ne 200 ]; then exit 1; fi