name: Deploy Spring Boot to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run API Integration Tests with Testcontainers
        run: ./gradlew apiTest

      # - name: Run UI Tests (Selenium)
      #   run: ./gradlew seleniumTest

      # - name: Run Performance Tests
      #   run: ./gradlew performanceTest

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "grading-system"
          package: build/libs/*.jar

      - name: Check Deployment Health
        run: |
          sleep 20  # Give the server some time to start
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://grading-system.azurewebsites.net/health)
          if [ "$STATUS" -ne 200 ]; then exit 1; fi