---
name: MegaLinter

on:
  push:
  pull_request:
    branches:
      - main
      - master

env:
  APPLY_FIXES: all
  APPLY_FIXES_EVENT: pull_request
  APPLY_FIXES_MODE: commit

jobs:
  lint:
    name: MegaLinter
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: MegaLinter
        uses: oxsecurity/megalinter@v8
        id: ml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          ENABLE_LINTERS: JAVA,JAVASCRIPT,HTML,CSS
          DISABLE_LINTERS: ALL

      - name: Upload Linter Reports
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: MegaLinter Reports
          path: |
            megalinter-reports
            mega-linter.log

      - name: Commit and push fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.ml.outputs.has_updated_sources == '1'
        with:
          commit_message: "[MegaLinter] Auto-fix applied"
          commit_user_name: "megalinter-bot"
          commit_user_email: "megalinter-bot@example.com"
